### ISSUE TITLE
Raffle script

### ISSUE THREAD

**Issue by SolalPirelli** [PolyProg/contest-scripts#1]
User input:
- Path to config file (e.g. "/mnt/d/dj_teams.json")
- List of team IDs to exclude (e.g. "12, 45, 83")
- DOMJudge base URL (sample: https://www.domjudge.org/demoweb, administrator logs in to /jury as admin/admin)
- DOMJudge session cookie ('domjudge_session')

Config file:
- Must contain 'teams' array of objects containing:
  - 'id' (int)
  - 'name' (string)
  - 'members' (array of strings)
  - (and possibly other stuff, to be ignored)

Preprocessing:
- Load $DOMJUDGE_BASE_URL/api/scoreboard (using the session cookie!)
- For each team, load its number of solved problems (score->num_solved)
- Creates an array of [(team_member, team_name, #problems_solved_by_team)]

UI contains one single button which:
- Randomly picks one team member from the array, using #problems_solved as weight
- Displays some kind of "suspense" message (in very large font), e.g. "." -> ". ." -> ". . ." taking 2-3 seconds
- Displays the team member name (in very large font), and the team name (below, in smaller font)
- Logs the team member / team name to a file (whose name can be hardcoded)
- Removes the team member from the array (i.e. ensures the person can't be picked again)

**Comment by robertre** [comment]
fyi this and #2 already exist from 2 years ago.

On Mar 26, 2017 17:13, "Solal Pirelli" <notifications@github.com> wrote:

User input:

   - Path to config file (e.g. "/mnt/d/dj_teams.json")
   - List of team IDs to exclude (e.g. "12, 45, 83")
   - DOMJudge base URL (sample: https://www.domjudge.org/demoweb,
   administrator logs in to /jury as admin/admin)
   - DOMJudge session cookie ('domjudge_session')

Config file:

   - Must contain 'teams' array of objects containing:
      - 'id' (int)
      - 'name' (string)
      - 'members' (array of strings)
      - (and possibly other stuff, to be ignored)

Preprocessing:

   - Load $DOMJUDGE_BASE_URL/api/scoreboard (using the session cookie!)
   - For each team, load its number of solved problems (score->num_solved)
   - Creates an array of [(team_member, team_name,
   #problems_solved_by_team)]

UI contains one single button which:

   - Randomly picks one team member from the array, using #problems_solved
   as weight
   - Displays some kind of "suspense" message (in very large font), e.g.
   "." -> ". ." -> ". . ." taking 2-3 seconds
   - Displays the team member name (in very large font), and the team name
   (below, in smaller font)
   - Logs the team member / team name to a file (whose name can be
   hardcoded)
   - Removes the team member from the array (i.e. ensures the person can't
   be picked again)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PolyProg/contest-scripts/issues/1>, or mute the thread
